language: python

python:
  - "3.8"

install:
  - pip install -r requirements/dev.txt

# Run the unit test
script:
  - coverage erase
  - coverage run tst/unit_test.py && coverage html

# Push the results back to codecov
after_success:
  - coveralls



git:
  depth: 1
  quiet: true
